"""add record.message

Revision ID: ad1f704412f4
Revises: c7d8b1ffb496
Create Date: 2020-12-26 17:18:04.879349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1f704412f4'
down_revision = 'c7d8b1ffb496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'message')
    # ### end Alembic commands ###
